# Generated by Django 2.2.2 on 2019-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('attachment', models.FileField(default='notfound', upload_to='media/attachment/%Y/%m/%d')),
            ],
        ),
    ]
