# Generated by Django 2.2.2 on 2019-06-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgt', '0003_auto_20190629_0509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
