# Generated by Django 2.2.2 on 2019-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgt', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'M'), (1, 'F'), (2, 'Other')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(default='notfound', upload_to='media/photo/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(default='notfound', upload_to='media/resume/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
