# Generated by Django 2.2.2 on 2019-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgt', '0006_auto_20190629_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='notfound', upload_to='media/photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='notfound', upload_to='media/photo/%Y/%m/%d'),
        ),
    ]
